### PR TITLE
Re-apply news updates changes while staying compatible with the Saradomin launcher

### PR DESCRIPTION
**Pull request by PureTryOut**
Third time's the charm.

So the launcher actually uses `/services/m=news/archives/latest.html` rather than `/services/m=news/latest.html`. Stupid of me to not properly check it...

### CODE REVIEW

**Comment by PureTryOut** [comment]
This time it works, no crashes! :tada: 

And now get the launcher to fetch it from the new place :sweat_smile:

**Comment by dginovker** [comment]
@PureTryOut It's mostly good, but for some reason https://2009scape.org/services/m=news/archives/latest.html is a bit off:

Before:
image

Now: 
image

**Comment by PureTryOut** [comment]
I know but tbh I don't really care for it, that page literally only exists to make the Saradomin Launcher work now, you can't actually get to that url from anywhere on the website.

The missing info comes from front matter and I can't easily get front matter from a different page, thus to prevent it from being incorrect when someone other than ryannathans posts something by defaulting to their info I opted to not choose any info at all.

**Comment by dginovker** [comment]
Hmm kk that's fine. I was actually trying to figure out why the Saradomin launch has different text

Before:
image

Now:
image



It's fine though :P

**Comment by PureTryOut** [comment]
That I don't know, the HTML output of the content of that post is the same as before afaik so not sure why it parses it differently now.

But eh, it's good enough imo :stuck_out_tongue:

**Comment by dginovker** [comment]
It looks like

`**Creature of Fenkenstrain** and **Rag and Bone Man** are now available!`

Turns into

`<p><strong>Creature of Fenkenstrain</strong> and <strong>Rag and Bone Man</strong> are now available!</p>`

Whereas it was previously

`<p><b>Creature of Fenkenstrain</b> and <b>Rag and Bone Man</b> are now available!</p>`

I'll update Saradomin to handle `<strong>` properly

**Comment by PureTryOut** [comment]
Ah that actually makes sense, interesting. While at it could you make it fetch the latest post from the RSS feed and use the link to the full post from there instead? We can't just remove the compatibility page of course because as you said not everyone will instantly update but we can at least make a start towards getting rid of it :wink: 

The RSS feed is now the most reliable way to find the correct URL to the latest news post.

**Comment by Ceikry** [comment]
Did either of you run these changes by Ryan (who uses a script to automatically update the website) before forcing changes?

**Comment by PureTryOut** [comment]
I did not know that was a thing, so no. Is that script hosted somewhere on Git so I could PR required changes?

**Comment by Ceikry** [comment]
You really should collaborate with the rest of the team rather than solely red bracket, who hasn't been an active contributor for years. You would have avoided multiple issues.

**Comment by Ceikry** [comment]
https://gitlab.com/2009scape/2009scape/-/blob/master/make-release.py?ref_type=heads

**Comment by PureTryOut** [comment]
Please calm your tone, I had no clue about this stuff and I'm not sure how I would know either. I just made a pull request for something I thought would be beneficial and everybody would be fine to request changes or deny the pull request. I had no say whatsoever in getting this merged. If you don't want @dginovker to merge things then maybe he shouldn't have merge rights.

I'll look into that script, it seems easy enough to update.

**Comment by Ceikry** [comment]
If you think my previous response was anything but calm, I am not quite sure what to tell you. Welcome to the internet?

**Comment by dginovker** [comment]
https://gitlab.com/2009scape/Saradomin-Launcher/-/merge_requests/50

**Comment by dginovker** [comment]
image

**Comment by dginovker** [comment]
> If you don't want @dginovker to merge things then maybe he shouldn't have merge rights.

Careful, that's how I lost merge rights on all the other repos

**Comment by Ceikry** [comment]
> image

PTO is the old man on the floor, I am the man spinning the noodle.

**Comment by PureTryOut** [comment]
> If you think my previous response was anything but calm, I am not quite sure what to tell you. Welcome to the internet?

The problem is in the words you choose to write your messages and previous comparable experiences with you.

Anyways it doesn't matter, I made the required changes in https://gitlab.com/2009scape/2009scape/-/merge_requests/1710.

**Comment by Ceikry** [comment]
You've barely spoken to me, much less so in the last year and a half. Please do not pretend you know me. Thank you for making the changes

**Pull request merged**
