### PR TITLE
Re-apply news updates changes while staying compatible with the Saradomin launcher

### PR DESCRIPTION
**Pull request by PureTryOut**
CC @dginovker.

Imo the launcher really shouldn't crash when it fails to retrieve news updates, it should continue working even if the site ever went down for whatever reason, but alas. Afaik it only uses `/services/m=news/latest.html` to retrieve the latest blog post and that should now work again.

### CODE REVIEW

**Comment by dginovker** [comment]
Yea it shouldn't crash, but even if we did update Saradomin people wouldn't have the latest launcher for years to come. So this is good. Thanks!

**Comment by PureTryOut** [comment]
Btw any chance you could not squash my commits on merge? I make them separate commits for a reason and I'd like to keep that history.

**Comment by PureTryOut** [comment]
Ugh what the hell, it still crashes... It's literally the same page as before though, how can that still happen?

**Comment by PureTryOut** [comment]
Problem is that I can't really test this easily myself locally. Maybe if I put 2009scape.org in my `/etc/hosts` to redirect to localhost...

**Comment by dginovker** [comment]
Well the good news is this will help me unsquash your commits

**Comment by PureTryOut** [comment]
Oh wait, it probably uses `/services/m=news/archive/latest.html` instead...?

**Comment by dginovker** [comment]
I'm on my way home now and have some plans after work, I can check what you make later tonight 🚁🦆

**Pull request merged**
