### PR TITLE
Use templates better to remove a ton of code duplication

### PR DESCRIPTION
**Pull request by PureTryOut**
Where it made sense I converted HTML pages to Markdown to ease writing and discourage custom styling as much as possible. These pages can still use custom HTML when necessary, and some do, but they are easier to read and understand now.

> 4,882 additions and 12,273 deletions.

Those are the numbers we like to see, love it.

### CODE REVIEW

**Review by dginovker — APPROVED** [review]

**Review by dginovker — APPROVED** [review]

**Comment by PureTryOut** [comment]
@Ceikry anything holding this back?

**Comment by dginovker** [comment]
@ryannathans Any opinion? I say we yeet it in

**Comment by ryannathans** [comment]
There are a lot of changes, does this impact my update script MR?

**Comment by PureTryOut** [comment]
It doesn't. The PR that does though is https://github.com/2009scape/2009scape.github.io/pull/243 which has already been merged, and https://gitlab.com/2009scape/2009scape/-/merge_requests/1710 updates your update script. There is no mention of this script in this repo btw so I had no clue it existed. Is there any reason for not having it in this repo instead of in the server one?

**Comment by PureTryOut** [comment]
@ryannathans and @Ceikry is there anything left to do here?

**Comment by downthecrop** [comment]
looks good to me.

**Pull request merged**
